name: CI

on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - "4.14"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Cache dist fonts
        uses: actions/cache@v4
        id: fonts-cache
        with:
          path: lib-satysfi/dist/fonts
          key: cache-dist-fonts-${{ hashFiles('download-fonts.sh') }}

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          allow-prerelease-opam: true
          opam-repositories: |
            satysfi-external: https://github.com/gfngfn/satysfi-external-repo.git
            default: https://github.com/ocaml/opam-repository.git

      - name: Install SATySFi dependencies
        run: opam install . --deps-only --with-doc --with-test

      - name: Build SATySFi
        run: opam exec -- make all

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Download fonts
        if: steps.fonts-cache.outputs.cache-hit != 'true'
        run: ./download-fonts.sh

      - name: Install SATySFi
        run: |
          opam install -y .
          ./install-libs.sh ~/.satysfi

      - name: Build demo docs
        run: |
          (cd demo; opam exec -- make)
          (cd doc; opam exec -- make)
          (cd tests; opam exec -- make)
